### PR TITLE
optional lf line break compatibility

### LINKED ISSUE #61: Support optional compatibility to LF as line break
Many (if not all) mainstream web servers, apache(`mod_upload`) and nginx(`upload module`) for instance, are compatible to request use LF as line break:

> https://github.com/Austinb/nginx-upload-module/blob/2.2/ngx_http_upload_module.c#L4123
> https://github.com/Austinb/nginx-upload-module/blob/2.2/ngx_http_upload_module.c#L4051
> http://apache.webthing.com/mod_upload/mod_upload.c L304

Would it be nessary for resty-upload module to support this too? Maybe an optional feature and closed by default?

To illustrate when it matters, a WAF may want to filter multipart form and use `lua-resty-upload`, where a malicious request can bypass its check for header:
```netcat
POST /submit.php HTTP/1.1
Host: target.com
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary6GpaBUxso7BnIrnA
Headers-Doesnt-Matters

------WebKitFormBoundary6GpaBUxso7BnIrnA
Content-Type: text/plain
Content-Disposition: form-data; name="something"; filename="doesnt_matter"

[LF rather than CRLF this line]
------WebKitFormBoundary6GpaBUxso7BnIrnA[LF rather than CRLF this line]
Content-Disposition: form-data; name="webshell.php"

malicious sciprt here
------WebKitFormBoundary6GpaBUxso7BnIrnA--
```

From WAF's point of view, below is a single line:
```
[LF rather than CRLF this line]
------WebKitFormBoundary6GpaBUxso7BnIrnA[LF rather than CRLF this line]
Content-Disposition: form-data; name="webshell.php"
```

therefore the boundary is missing and the second uploaded file(including its headers) is seen as part of the first file's body, and protected server still see it as two files.

We can make up more method to bypass WAF based on this.

### PR DESCRIPTION
**Pull request by suikabreaker**
fix #61

### CODE REVIEW

**Comment by suikabreaker** [comment]
@xiaocang may you spend some time on this PR?

**Comment by zhuizhuhaomeng** [comment]
> @xiaocang may you spend some time on this PR?

@suikabreaker  tks for you PR.
We need to add some test cases to cover the new feature.

**Comment by suikabreaker** [comment]
I've mistakenly add the feature based on a fork... and this PR contains two new featrues. I'll rearrange it.

**Comment by suikabreaker** [comment]
> > @xiaocang may you spend some time on this PR?
> 
> @suikabreaker tks for you PR. We need to add some test cases to cover the new feature.

@zhuizhuhaomeng I've split this PR into two, each implements one feature, and added tests for them. May you review those PRs?

https://github.com/openresty/lua-resty-upload/pull/64

https://github.com/openresty/lua-resty-upload/pull/63

**Comment by xiaocang** [comment]
ok, I'll check it.

**Pull request closed without merging**
